### ISSUE TITLE
check exercise 1

### ISSUE THREAD

**Issue by luketudge** [luketudge/intro-stats-2021#4]
@maia-sh the first exercise is up. In 'exercises/exercise_1_intro.Rmd'. It is just an Rmarkdown document with empty code chunks to be filled in. I remember when we discussed options like learnr and interactive exercises we decided against it. But in case you have been playing with any other options in the meantime and would like to try them out, you can have a go at adapting it. Or if anything useful occurs to you that could be added to the Rmarkdown.

Otherwise just go ahead and close this issue already.

**Comment by maia-sh** [comment]
Hi Luke, just a few comments/thoughts:

- {learnr}: I looked into [learnr publishing](https://rstudio.github.io/learnr/publishing.html) options beyond a shiny server and see there is a convenient function (`learnr::run_tutorial()`) for spinning it up locally. I'll take a look at this but may not be in time for this first exercise. 
- variable names: this is more style but I've found it easiest to keep to all lowercase (lower snake), especially for collaboration, so would change `Birth` to `birth`. Also tidystyle: https://style.tidyverse.org/syntax.html#object-names
- I see the convenience of teaching a `setwd()` approach first, and this is indeed how I learned, but working from Rprojects and {here} makes things so much easier in the bigger picture. I know that would be more start-up investment, but perhaps that could have a value. I think the first few chapters of [Jenny Bryant's What they forgot to teach you](https://rstats.wtf/project-oriented-workflow.html) offer some good resources if this were a direction of interest. I see the value in starting off in project but if this is too much, this is the type of thing I'd be happy to cover later in a "reproducible workflow" session if there's time.

**Comment by luketudge** [comment]
@maia-sh Thanks!

* learnr publishing: This sounds good. Would be great if you look into it. No rush. If it involves getting the students to run something locally then it can wait until the next practical session, to avoid overloading them with lots of new stuff to do.
* variable names / tidystyle: As an R dinosaur, I have been very slow in catching up to tidystyle. If you can face the tedium of fixing this in the exercise, that would be great. We might as well get the students used to it from the beginning. Just let me know if you can afford to take it on, then create a pull request for it. The variable names are like that in the csv data file as well unfortunately, so that would need changing too.
* I won't be teaching them `setwd()` at all, except to mention that they should never use it, for the same reasons Jenny Bryant gives. I put `getwd()` in the exercise just as an attempt to get people to understand that there is such a thing as a working directory and that it matters. Again for dinosaury reasons I am not up to speed with Rprojects. I have always just relied on the fact that Rmarkdown documents by default run and knit from the directory in which they are located (right?) In the current circumstances I won't be able to bone up on projects and {here} quick enough to make it part of the tutorials unfortunately, so that would be really great if you could make it part of your session on reproducibility.

**Comment by maia-sh** [comment]
Hi Luke,
- learnr. sounds good. I'm quite curious so i will go ahead and let you know if I get something done after work today.
- variable names. branched and made the edits quite fast with `janitor::clean_names()` and will pr
- sounds good! rprojects and here are bookmarked for reproducibility session
